
project_id = "horzlrlmbfivzrmycauu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[analytics]
enabled = false

[realtime]
enabled = true

# Enable Edge Functions
[functions]
enabled = true
serve_port = 54325

[functions.store-summary]
verify_jwt = true
