
project_id = "horzlrlmbfivzrmycauu"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[functions]
[functions.analyze-shelf-image]
verify_jwt = true
